export interface Listing {
  type: string,
  name: string,
  bedrooms: number,
  bathrooms: number,
  parking: boolean,
  furnished: boolean,
  address: string,
  description: string,
  offer: boolean,
  regularPrice: number,
  discountedPrice: number,
  latitude: number,
  longitude: number,
  images: {},
  imgUrls?: string[],
  timestamp?: any,
  id: number,
};